version: "3.7"

services:
  elasticsearch:
    container_name: ast-elasticsearch
    image: ast-elasticsearch:latest
    # image: elasticsearch:7.1.1
    # hostname: ast-elasticsearch
    restart: always
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #- ./.es_data:/usr/share/elasticsearch/data
      - es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: ast_elastic
    networks:
      - ast-elk
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

  logstash:
    container_name: ast-logstash
    image: ast-logstash:latest
    # image: logstash:7.1.1
    # hostname: ast-logstash
    restart: always
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 5044:5044 # tcp
      # - 9600:9600 # API port
      # - 12201:12201 # gelf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - ast-elk
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

  kibana:
    container_name: ast-kibana
    image: ast-kibana:latest
    # image: kibana:7.1.1
    # hostname: ast-kibana
    restart: always
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - 5601:5601
    networks:
      - ast-elk
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m

# use docker volume to persist ES data outside of a container.
volumes:
  es_data:

networks:
  ast-elk:
    driver: bridge
