# https://github.com/elastic/apm-server
# FROM docker.elastic.co/apm/apm-server:7.2.0
FROM apm-server:7.2.0

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
